import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
      </main>

      <footer>
        <div className="copyright">
          <h5>Created by Liam Pugh using Next.JS</h5>
        </div>
      </footer>
    </div>
  )
}
