import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Textblock from '../components/Textblock'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar /> 
        <Textblock subtitle={'A box to put contents in'}
        paragraph={'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'} />
        
      </main>

      <footer>
        <div className="copyright">
          <h5>Created by Liam Pugh using Next.JS</h5>
        </div>
      </footer>
    </div>
  )
}
